run:
  timeout: 5m
  build-tags: "golangcilint unit integration e2e azurite"

linters:
  enable-all: true
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - depguard
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen # DONT re-enable funlen please
    - gci
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofumpt
    - golint
    - gomoddirectives
    - gomnd
    - gosec
    - gosimple
    - ifshort
    - inamedparam
    - interfacer
    - interfacebloat
    - ireturn
    - maligned
    - maintidx
    - misspell
    - musttag
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nestif
    - nolintlint
    - nonamedreturns
    - nosnakecase
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - revive
    - rowserrcheck
    - scopelint
    - structcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unparam
    - unused
    - usestdlibvars
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - wsl
    - wrapcheck

linters-settings:
  funlen:
    lines: 350
    statements: 135

  depguard:
    list-type: blacklist
    packages:
      - github.com/sirupsen/logrus # only allowed in logutils

  dupl:
    threshold: 100

  errorlint:
    errorf: false
    errorf-multi: true
    asserts: true
    comparison: true

  exhaustive:
    check:
      - switch
      - map
    check-generated: true
    default-signifies-exhaustive: true
    ignore-enum-members: "Example.+"
    ignore-enum-types: "Example.+"
    package-scope-only: true
    explicit-exhaustive-switch: false
    explicit-exhaustive-map: false

  gci:
    local-prefixes: github.com/datatrails/go-datatrails-merklelog

  goconst:
    min-len: 2
    min-occurrences: 2

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

  gocognit:
    min-complexity: 75

  gocyclo:
    min-complexity: 10

  goimports:
    local-prefixes: github.com/golangci/golangci-lint

  golint:
    min-confidence: 0

  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - Infof
          - Warnf
          - Errorf
          - Fatalf

  lll:
    line-length: 500

  maligned:
    suggest-new: true

  misspell:
    locale: UK

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
