---
version: '3'

# This Taskfile represents the primary control surface for developers interacting with
# this component.
#
# Primary "configure/build/deploy/test" tasks must be provided directly in this top level
# taskfile
#
# Infrequently used or pure sub-tasks should be in subservient taskfiles and included
# here.
#
# All tasks that are expected to be run directly by developers must have a meaningful
# 'desc' with all optional variables defined, in this file or in included files.
#
# All tasks that are internal sub-tasks only should have a meaningful 'summary'.
#
includes:
  codequality:
    taskfile: ./taskfiles/Taskfile_codequality.yml
    dir: ./taskfiles
  azurite:
    taskfile: ./taskfiles/Taskfile_azurite.yml
    dir: ./taskfiles
  gobuild:
    taskfile: ./taskfiles/Taskfile_gobuild.yml
    dir: ./taskfiles
  gotest:
    taskfile: ./taskfiles/Taskfile_gotest.yml
    dir: ./taskfiles

tasks:

  build:
    desc: ensure go build works for all modules
    cmds:
      - task: gobuild:go:build

  build:fast:
    desc: ensure go build works for all modules
    cmds:
      - task: gobuild:go:build

  build:clean:
    desc: ensure go build works for all modules
    cmds:
      - task: gobuild:go:build

  format:
    desc: formats the code correctly
    cmds:
      - task: codequality:format 

  lint:
    desc: lints the go code
    cmds:
      - task: codequality:lint 

  go:modules:
    desc: tidies the go modules
    cmds: 
      - task: codequality:modules

  test:unit:
    desc: run the unit tests
    cmds:
      - task: gotest:go:unit

  test:integration:
    desc: run the azurite integration tests
    cmds:
     - task: azurite:preflight
     - task: gotest:go:azurite