name: push

on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # make tags available for the build
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false

      - name: Install Go quality tools
        run: |
          go install golang.org/x/tools/cmd/goimports@v0.1.7
          go install github.com/axw/gocov/gocov@v1.1.0
          go install github.com/jstemmer/go-junit-report/v2@v2.1.0
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.60.3

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bootstrap
        run: |
          task bootstrap

      - name: Unit tests
        run: |
          # Note: it is by design that we don't use the builder
          task test:unit
      - name: Integration tests
        run: |
          # Note: it is by design that we don't use the builder
          task test:integration
      - name: DataTrails public log tests
        run: |
          # Note: it is by design that we don't use the builder
          task test:datatrails:public

  systemtest:
    name: Built binary tests
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          # make tags available for the build
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23" # Specify the Go version you need

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: "3.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: |
          task bootstrap
          task build
          export VERACITY_INSTALL=$(readlink -f ./veracity) >> $GITHUB_ENV
          ./veracity --help
          ./veracity --version

      - name: Test the built binary
        run: |
          echo "Veracity Installation Path: $VERACITY_INSTALL"
          task test:binary

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: ./tests/systemtest/res.xml
